[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = 'foundry-test'
cache_path  = 'foundry-cache'

solc_version = "0.8.17"
#remappings = [
#    "@openzeppelin/=node_modules/@openzeppelin/",
#    "hardhat/=node_modules/hardhat/",
#    "operator-filter-registry/=node_modules/operator-filter-registry/",
#]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config