[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "operator-filter-registry/=node_modules/operator-filter-registry/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config